[package]
name = "scrap"
version = "0.1.0"
authors = ["fahmi irsyad khairi <fahmiirsyad10@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.14"
scraper = "0.10.0"
select = "0.4.2"
prettytable-rs = "0.8.0"

